language: c

sudo: false

os:
  - linux

compiler:
  - gcc-4.9
  - gcc-5
  - gcc-6
  - clang

env:
  matrix:
   - CONF="shared" STACK=0
   - CONF="static" STACK=0
   - CONF="shared-poll" STACK=0
   - CONF="shared" STACK=1
   - CONF="static" STACK=1
   - CONF="shared-poll" STACK=1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - gcc-5
      - gcc-6
      - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ $CC == "gcc-5" ]]; then brew install gcc5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ $CC == "gcc-6" ]]; then brew install gcc6; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ $CC == "clang" ]]; then brew install llvm38; fi

install:
  - if [[ $CONF == "shared" ]]      && (( $STACK == 0 )); then ./autogen.sh && ./configure && make; fi
  - if [[ $CONF == "static" ]]      && (( $STACK == 0 )); then ./autogen.sh && ./configure --disable-shared && make; fi
  - if [[ $CONF == "shared-poll" ]] && (( $STACK == 0 )); then ./autogen.sh && ./configure CFLAGS=-DDILL_POLL && make; fi
  - if [[ $CC == gcc* ]] && (( $STACK == 1 )) && [[ $CONF == "shared" ]]; then ./autogen.sh && ./configure CFLAGS="-fstack-protector-strong" && make; fi
  - if [[ $CC == gcc* ]] && (( $STACK == 1 )) && [[ $CONF == "static" ]]; then ./autogen.sh && ./configure --disable-shared CFLAGS="-fstack-protector-strong" && make; fi
  - if [[ $CC == gcc* ]] && (( $STACK == 1 )) && [[ $CONF == "shared-poll" ]]; then ./autogen.sh && ./configure CFLAGS="-DDILL_POLL -fstack-protector-strong" && make; fi
  - if [[ $CC == clang* ]] && (( $STACK == 1 )) && [[ $CONF == "shared" ]]; then ./autogen.sh && ./configure CFLAGS="-fstack-protector -fsanitize=safe-stack" && make; fi
  - if [[ $CC == clang* ]] && (( $STACK == 1 )) && [[ $CONF == "static" ]]; then ./autogen.sh && ./configure --disable-shared CFLAGS="-fstack-protector -fsanitize=safe-stack" && make; fi
  - if [[ $CC == clang* ]] && (( $STACK == 1 )) && [[ $CONF == "shared-poll" ]]; then ./autogen.sh && ./configure CFLAGS="-DDILL_POLL -fstack-protector -fsanitize=safe-stack" && make; fi

script:
  - make check

after_failure:
  - for f in tests/*.log; do echo; echo "${f}:"; cat $f; done;
  - cat test-suite.log

notifications:
  email: false
