language: c

matrix:
  include:
  - env: DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STACK=1 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 STACK=1 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STACK=1 DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 STACK=1 DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STACK=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 STACK=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STACK=1 DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 STACK=1 DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STACK=1 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 STACK=1 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STACK=1 DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 STACK=1 DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STACK=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 STACK=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STACK=1 DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 STACK=1 DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STACK=1 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 STACK=1 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STACK=1 DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 STACK=1 DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STACK=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 STACK=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STACK=1 DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 STACK=1 DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STACK=1 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 STACK=1 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STACK=1 DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 STACK=1 DEBUG=1 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STACK=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 STACK=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STACK=1 DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 STACK=1 DEBUG=1 OPT=-O3 DIST='PRECISE'
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: POLL=1 DIST='PRECISE'
    os: linux
    compiler: gcc
  - env: STACK=1 OPT=-O3 DIST='TRUSTY'
    os: linux
    compiler: gcc-6
    dist: trusty
    sudo: required
    before_install:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo apt-get -qq update
      - sudo apt-get install -y gcc-6
  - env: OPT=-O3 DIST='TRUSTY'
    os: linux
    compiler: clang-4.0
    dist: trusty
    sudo: required
    before_install:
      - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
      - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
      - sudo apt-get -qq update
      - sudo apt-get install -y clang-4.0
  - env: STACK=1 OPT=-O3 DIST='TRUSTY'
    os: linux
    compiler: clang-4.0
    dist: trusty
    sudo: required
    before_install:
      - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
      - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main'
      - sudo apt-get -qq update
      - sudo apt-get install -y clang-4.0
  - env:
    os: osx
    compiler: clang
  - env: STATIC=1
    os: osx
    compiler: clang
  - env:
    os: osx
    compiler: gcc
  - env: POLL=1
    os: osx
    compiler: gcc
  - env: STATIC=1
    os: osx
    compiler: gcc
  - env: OPT=-O3
    os: osx
    compiler: clang-3.9
    before_install:
      - brew update
      - brew install llvm
      - export LDFLAGS=-L/usr/local/opt/llvm/lib
      - export CPPFLAGS=-L/usr/local/opt/llvm/include
      - export PATH=/usr/local/opt/llvm/bin:$PATH
  - env: OPT=-O3
    os: osx
    compiler: gcc-6
    before_install:
      - brew update
      - brew install gcc6
      - export LDFLAGS=-L/usr/local/opt/gcc6/lib
      - export CPPFLAGS=-L/usr/local/opt/gcc6/include
      - export PATH=/usr/local/opt/gcc6/bin:$PATH

install:
  - if [[ $CC == gcc* ]] && [[ "${STACK+1}" == "1" ]]; then CFLAGS="$CFLAGS -fstack-protector-all"; fi
  - if [[ $CC == clang* ]] && [[ "${STACK+1}" == "1" ]]; then CFLAGS="$CFLAGS -fstack-protector"; fi
  - ./autogen.sh && ./configure CFLAGS="$CFLAGS ${POLL+-DDILL_POLL} ${OPT}" CPPFLAGS="$CPPFLAGS" LDFLAGS="$LDFLAGS" ${STATIC+--disable-shared} ${DEBUG+--enable-debug} && make V=1

script:
  - make check

after_failure:
  - for f in tests/*.log; do echo; echo "${f}:"; cat $f; done;
  - cat test-suite.log

notifications:
  email: false
