language: c

matrix:
  include:
  - env:
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STACK=1
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 STACK=1
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: DEBUG=1
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 DEBUG=1
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STACK=1 DEBUG=1
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 STACK=1 DEBUG=1
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: OPT=-O3
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 OPT=-O3
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STACK=1 OPT=-O3
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 STACK=1 OPT=-O3
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: DEBUG=1 OPT=-O3
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STACK=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env: STATIC=1 STACK=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: gcc-4.9
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
  - env:
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STACK=1
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 STACK=1
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: DEBUG=1
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 DEBUG=1
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STACK=1 DEBUG=1
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 STACK=1 DEBUG=1
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: OPT=-O3
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 OPT=-O3
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STACK=1 OPT=-O3
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 STACK=1 OPT=-O3
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: DEBUG=1 OPT=-O3
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STACK=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env: STATIC=1 STACK=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: gcc-5
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-5
  - env:
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STACK=1
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 STACK=1
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: DEBUG=1
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 DEBUG=1
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STACK=1 DEBUG=1
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 STACK=1 DEBUG=1
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: OPT=-O3
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 OPT=-O3
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STACK=1 OPT=-O3
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 STACK=1 OPT=-O3
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: DEBUG=1 OPT=-O3
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STACK=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env: STATIC=1 STACK=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: gcc-6
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-6
  - env:
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STACK=1
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 STACK=1
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: DEBUG=1
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 DEBUG=1
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STACK=1 DEBUG=1
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 STACK=1 DEBUG=1
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: OPT=-O3
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 OPT=-O3
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STACK=1 OPT=-O3
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 STACK=1 OPT=-O3
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: DEBUG=1 OPT=-O3
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STACK=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env: STATIC=1 STACK=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: clang
    sudo: false
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - clang
  - env:
    os: linux
    compiler: clang-3.5
  - env: STATIC=1
    os: linux
    compiler: clang-3.5
  - env: STACK=1
    os: linux
    compiler: clang-3.5
  - env: STATIC=1 STACK=1
    os: linux
    compiler: clang-3.5
  - env: DEBUG=1
    os: linux
    compiler: clang-3.5
  - env: STATIC=1 DEBUG=1
    os: linux
    compiler: clang-3.5
  - env: STACK=1 DEBUG=1
    os: linux
    compiler: clang-3.5
  - env: STATIC=1 STACK=1 DEBUG=1
    os: linux
    compiler: clang-3.5
  - env: OPT=-O3
    os: linux
    compiler: clang-3.5
  - env: STATIC=1 OPT=-O3
    os: linux
    compiler: clang-3.5
  - env: STACK=1 OPT=-O3
    os: linux
    compiler: clang-3.5
  - env: STATIC=1 STACK=1 OPT=-O3
    os: linux
    compiler: clang-3.5
  - env: DEBUG=1 OPT=-O3
    os: linux
    compiler: clang-3.5
  - env: STATIC=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: clang-3.5
  - env: STACK=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: clang-3.5
  - env: STATIC=1 STACK=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: clang-3.5
  - env:
    os: linux
    compiler: clang-3.8
  - env: STATIC=1
    os: linux
    compiler: clang-3.8
  - env: STACK=1
    os: linux
    compiler: clang-3.8
  - env: STATIC=1 STACK=1
    os: linux
    compiler: clang-3.8
  - env: DEBUG=1
    os: linux
    compiler: clang-3.8
  - env: STATIC=1 DEBUG=1
    os: linux
    compiler: clang-3.8
  - env: STACK=1 DEBUG=1
    os: linux
    compiler: clang-3.8
  - env: STATIC=1 STACK=1 DEBUG=1
    os: linux
    compiler: clang-3.8
  - env: OPT=-O3
    os: linux
    compiler: clang-3.8
  - env: STATIC=1 OPT=-O3
    os: linux
    compiler: clang-3.8
  - env: STACK=1 OPT=-O3
    os: linux
    compiler: clang-3.8
  - env: STATIC=1 STACK=1 OPT=-O3
    os: linux
    compiler: clang-3.8
  - env: DEBUG=1 OPT=-O3
    os: linux
    compiler: clang-3.8
  - env: STATIC=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: clang-3.8
  - env: STACK=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: clang-3.8
  - env: STATIC=1 STACK=1 DEBUG=1 OPT=-O3
    os: linux
    compiler: clang-3.8
  - env: POLL=1
    os: linux
    compiler: gcc
  - env: STACK=1 OPT=-O3 TRUSTY=1
    os: linux
    compiler: gcc-6
    dist: trusty
    sudo: required
    before_install:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo add-apt-repository ppa:paulo-miguel-dias/llvm-snapshot -y
      - sudo apt-get -qq update
      - sudo apt-get install -y gcc-6
  - env: OPT=-O3 TRUSTY=1
    os: linux
    compiler: clang-4.0
    dist: trusty
    sudo: required
    before_install:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo add-apt-repository ppa:paulo-miguel-dias/llvm-snapshot -y
      - sudo apt-get -qq update
      - sudo apt-get install -y llvm-toolchain-snapshot
  - env: STACK=1 OPT=-O3 TRUSTY=1
    os: linux
    compiler: clang-4.0
    dist: trusty
    sudo: required
    before_install:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
      - sudo add-apt-repository ppa:paulo-miguel-dias/llvm-snapshot -y
      - sudo apt-get -qq update
      - sudo apt-get install -y llvm-toolchain-snapshot
  - env:
    os: osx
    compiler: clang
  - env: STATIC=1
    os: osx
    compiler: clang
  - env:
    os: osx
    compiler: gcc
  - env: POLL=1
    os: osx
    compiler: gcc
  - env: STATIC=1
    os: osx
    compiler: gcc
  - env: OPT=-O3
    os: osx
    compiler: clang-3.9
    before_install:
      - brew update
      - brew install llvm
  - env: OPT=-O3
    os: osx
    compiler: gcc-6
    before_install:
      - brew update
      - brew install gcc6

install:
  - if [[ $CC == gcc* ]] && [[ "${STACK+1}" == "1" ]]; then CFLAGS="$CFLAGS -fstack-protector-all"; fi
  - if [[ $CC == clang* ]] && [[ "${STACK+1}" == "1" ]]; then CFLAGS="$CFLAGS -fstack-protector"; fi
  - ./autogen.sh && ./configure CFLAGS="$CFLAGS ${POLL+-DDILL_POLL} ${OPT}" ${STATIC+--disable-shared} ${DEBUG+--enable-debug} && make V=1

script:
  - make check

after_failure:
  - for f in tests/*.log; do echo; echo "${f}:"; cat $f; done;
  - cat test-suite.log

notifications:
  email: false
