language: c

sudo: false

os:
  - osx
  - linux

compiler:
  - gcc-4.9
  - gcc-5
  - gcc-6
  - clang

env:
  matrix:
   - CONF="shared"
   - CONF="static"
   - CONF="shared-poll"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - gcc-5
      - gcc-6
      - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc6; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm38; fi

install:
  - if [[ $CONF == "shared" ]]; then ./autogen.sh && ./configure && make; fi
  - if [[ $CONF == "static" ]]; then ./autogen.sh && ./configure --disable-shared && make; fi
  - if [[ $CONF == "shared-poll" ]]; then ./autogen.sh && ./configure CFLAGS=-DDILL_POLL && make; fi

script:
  - make check

after_failure:
  - for f in tests/*.log; do echo; echo "${f}:"; cat $f; done;
  - cat test-suite.log

notifications:
  email: false
