language: c

sudo: false

os:
  - linux

compiler:
  - gcc-4.9
  - gcc-5
  - gcc-6
  - clang

env:
  matrix:
   - DEFAULT=1
   - M32=1
   - POLL=1
   - POLL=1 M32=1
   - STATIC=1
   - STATIC=1 M32=1
   - STATIC=1 POLL=1
   - STATIC=1 POLL=1 M32=1
   - STACK=1 DEFAULT=1
   - STACK=1 M32=1
   - STACK=1 POLL=1
   - STACK=1 POLL=1 M32=1
   - STACK=1 STATIC=1
   - STACK=1 STATIC=1 M32=1
   - STACK=1 STATIC=1 POLL=1
   - STACK=1 STATIC=1 POLL=1 M32=1


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - gcc-5
      - gcc-6
      - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ $CC == "gcc-5" ]]; then brew install gcc5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ $CC == "gcc-6" ]]; then brew install gcc6; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ $CC == "clang" ]]; then brew install llvm38; fi

install:
  - if [[ $CC == gcc* ]] && [[ "${STACK+1}" == "1" ]]; then CFLAGS="$CFLAGS -fstack-protector-all"; fi
  - if [[ $CC == clang* ]] && [[ "${STACK+1}" == "1" ]]; then CFLAGS="$CFLAGS -fstack-protector"; fi
  - ./autogen.sh && ./configure CFLAGS="$CFLAGS ${POLL+-DDILL_POLL} ${M32+-Dm32}" ${STATIC+--disable-shared} && make

script:
  - make check

after_failure:
  - for f in tests/*.log; do echo; echo "${f}:"; cat $f; done;
  - cat test-suite.log

notifications:
  email: false
